Use shelljs instead of fs.mkdirSync for recursive directory creation
Problem:

In Node v8.9.0 (current LTS release), Pe-Epub would fail to build an
epub properly due to an inability to create recursive sub-directories in
the course of tasks like building an OPF file.

For example, the following error is thrown when running most of the
tests:

```
Error: ENOENT: no such file or directory, mkdir '/Users/eric/dev/pe-epub/epubs/22ba6566-84a9-87ed-3039-59e6c9835cae/
```

Pe-Epub is attempting to create an `epubs` directory with a subdirectory
of the randomly-generated book ID, but (at least in Node v8) fs.mkdir
can't handle creation of multiple nested directories at once.

Proposed solution:

This commit fixes this error by modifying the Peepub._epubPath() method
to use shell.mkdir() with the '-p' flag to support recursive directory
creation. Shelljs works on both Unix platforms as well as Windows.

After this change, all tests pass locally except one of the TOC specs
("TOC functionality will create a toc link to the first page if you
haven't put any pages in the TOC"). I believe this is a separate issue
which can be addressed in a later commit.